### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by amilajack** [ironSource/rename-import-dll#3]
I'm trying to figure out how to use this library but I can't because there's no instructions

**Comment by issacg** [comment]
At one point there used to be a blog post which, I think, covered usage.  I'll try to hunt it down.

In the meantime, assuming you've built the utility, you run it as follows:

```rid.exe <path-to-module> <old-exe-name> <new-exe-name>``

So for example, assuming your module lives at ./node_modules/foo/foo.node and you are renaming nw.exe to mynw.exe, you'd do ```rid.exe node_modules\foo\foo.node nw.exe mynw.exe```
